/* eslint-disable */

const dummyData = [
  {
    id: 3873,
    plannedTime: '2021-06-19T07:00:00Z',
    duration: '01:30:00',
    startTime: '2021-06-18T21:38:12.07Z',
    lines: {
      title: 'Инвестиции в кадры: партнерство бизнеса и образования в креативных индустриях',
      description:
        'Россия стоит на пороге перехода от «сырьевой» экономики к экономике идей. Совершить этот переход возможно, если решить проблему кадрового дефицита. Вместо того чтобы постфактум искать талантливых выпускников, бизнес может непосредственно принимать активное участие в образовании будущих специалистов. ',
      title_short: 'ИНВЕСТИЦИИ В КАДРЫ',
      speakers: [{ name: 'КАЛИТИН МИХАИЛ', title: 'ОСНОВАТЕЛЬ, ГЕН. ДИРЕКТОР STRUCTURA AGENCУ' }],
    },
    face: null,
    type: 'episode',
    data: {},
    speakers: [{ name: 'КАЛИТИН МИХАИЛ' }],
    stopTime: '2021-06-18T21:38:13.227Z',
  },
  {
    id: 3874,
    plannedTime: '2021-06-19T08:30:00Z',
    duration: '01:30:00',
    startTime: '2021-06-18T21:38:13.227Z',
    lines: {
      title: 'Креативные индустрии: статистика, экспорт и интеграция в мировую экономику',
      description:
        'Разработка национальных программ и проектов творческих (креативных) индустрии – часть большой глобальной работы по развитию креативной экономики, которую ведут многие международные организации. Формирование приоритетов в сфере творческих индустрий, стандартов управления и статистического учета важно для России, где пока нет ясности федеральных и региональных данных по сектору творческой экономики.',
      title_short: 'КРЕАТИВНЫЕ ИНДУСТРИИ',
      speakers: [
        {
          name: 'Владимир Владимирович Александров',
          title: 'ОСНОВАТЕЛЬ, ГЕН. ДИРЕКТОР STRUCTURA AGENCУ',
        },
        { name: 'Крамольный Петр Иванович' },
      ],
    },
    face: null,
    type: 'episode',
    data: {},
    speakers: [{ name: 'Владимир Владимирович Александров' }, { name: 'Крамольный Петр Иванович' }],
    stopTime: '2021-06-18T21:38:14.937Z',
  },
  {
    id: 3875,
    plannedTime: '2021-06-19T10:00:00Z',
    duration: '01:00:00',
    startTime: '2021-06-18T21:38:14.937Z',
    lines: { title: 'Обед', description: '', title_short: 'ОБЕД' },
    face: null,
    type: 'break',
    data: {},
    stopTime: '2021-06-18T21:38:17.543Z',
  },
  {
    id: 3876,
    plannedTime: '2021-06-19T11:00:00Z',
    duration: '01:30:00',
    startTime: '2021-06-18T21:38:17.543Z',
    lines: {
      title: 'Культура эпохи локдауна: цифровизация – источник вдохновения или вынужденная мера?',
      description:
        'Адаптируясь к новой цифровой реальности, деятели культуры вынужденно оказались в поисках новых форм творческого самовыражения',
      title_short: 'КУЛЬТУРА ЭПОХИ ЛОКДАУНА',
      speakers: [{ name: 'Amalia Walter' }, { name: 'Lewys Dorsey' }],
    },
    face: null,
    type: 'episode',
    data: {},
    speakers: [{ name: 'Amalia Walter' }, { name: 'Lewys Dorsey' }],
    stopTime: null,
  },
  {
    id: 3877,
    plannedTime: '2021-06-19T11:30:00Z',
    duration: '01:30:00',
    startTime: null,
    lines: {
      title: 'Кто на ком зарабатывает: блогеры на бизнесе или бизнес на блогерах?',
      description:
        'Инфлюенс-маркетинг – один из самых быстрорастущих рекламных каналов. Каждый день аудитория социальных сетей и мессенджеров увеличивается по всему миру, а крупные бренды перераспределяют ресурсы, чтобы инвестировать в рекламу у блогеров.',
      title_short: 'КТО НА КОМ ЗАРАБАТЫВАЕТ',
    },
    face: null,
    type: 'episode',
    data: {},
    stopTime: null,
  },
  {
    id: 3878,
    plannedTime: '2021-06-19T13:00:00Z',
    duration: '00:40:00',
    startTime: null,
    lines: {
      title: 'Мировые арт-столицы',
      description: 'Мировые арт-столицы: чего не хватает российским мегаполисам, чтобы получить такой статус?',
      title_short: 'МИРОВЫЕ АРТ-СТОЛИЦЫ',
    },
    face: null,
    type: 'episode',
    data: {},
    stopTime: null,
  },
  {
    id: 3879,
    plannedTime: '2021-06-19T13:40:00Z',
    duration: '00:20:00',
    startTime: null,
    lines: { title: 'Coffee-Break', description: '', title_short: 'COFFEE-BREAK' },
    face: null,
    type: 'break',
    data: {},
    stopTime: null,
  },
  {
    id: 3880,
    plannedTime: '2021-06-19T14:00:00Z',
    duration: '00:25:00',
    startTime: null,
    lines: {
      title: 'Поддержка молодых талантов – основа для будущего креативной экономики',
      description: 'При поддержке фонда «Искусство, наука и спорт»',
      title_short: 'ПОДДЕРЖКА МОЛОДЫХ ТАЛАНТОВ – ОСНОВА ДЛЯ БУДУЩЕГО КРЕАТИВНОЙ ЭКОНОМИКИ',
    },
    face: null,
    type: 'episode',
    data: {},
    stopTime: null,
  },
  {
    id: 3967,
    plannedTime: '2021-08-13T21:00:00Z',
    duration: '00:10:00',
    startTime: '2021-08-14T21:36:33.613Z',
    lines: { title: '1', description: null },
    face: null,
    type: 'episode',
    data: {},
    stopTime: '2021-08-14T21:36:36.86Z',
  },
  {
    id: 3966,
    plannedTime: '2021-08-13T21:10:00Z',
    duration: '00:20:00',
    startTime: '2021-08-14T21:36:36.86Z',
    lines: { title: '2', description: null },
    face: null,
    type: 'episode',
    data: {},
    stopTime: '2021-08-14T21:49:25.95Z',
  },
];

export default dummyData;
